domain_prompts = {
    "photo": [
        "a real photo",
        "a natural photograph",
        "a realistic photographic image",
        "a color photograph",
        "a close-up photo",
    ],
    "cartoon": [
        "a cartoon image",
        "a colorful cartoon illustration",
        "an animated cartoon image",
        "a comic style illustration",
        "a simple cartoon drawing",
        "a brightly colored cartoon image",
        "a vivid colorful animated illustration",
        "a saturated cartoon drawing",
    ],
    "deviantart": [
        "a deviantart digital artwork",
        "a digital art illustration",
        "a highly stylized digital artwork",
    ],
    "embroidery": [
        "an embroidered artwork",
        "a stitched embroidery design",
        "an image sewn with thread",
    ],
    "graffiti": [
        "a graffiti artwork on a wall",
        "a spray-painted graffiti image",
        "street art graffiti",
    ],
    "graphic": [
        "a vector graphic design",
        "a flat graphic illustration",
        "a clean digital graphic image",
    ],
    "misc": [
        "a miscellaneous stylized image",
        "a mixed style artwork",
        "an unusual artistic image",
    ],
    "origami": [
        "an origami paper figure",
        "a folded paper object",
        "a paper craft origami image",
    ],
    "sculpture": [
        "a three-dimensional sculpture",
        "a sculpted object",
        "a carved statue artwork",
    ],
    "sketch": [
        "a black and white sketch",
        "a grayscale sketch",
        "a line drawing",
        "a contour drawing",
        "an outline drawing",
        "a monochrome line drawing",
        "a black and white line art image",
        "a clean black outline drawing",
        "a sparse black line drawing on white background",
        "a sketch with only object contours",
        "a white background with thin black outlines",
        "a monochrome contour sketch",
        "a simple object outline drawing",
        "a line-art sketch with no shading",
        "a black ink outline drawing",
        "a sketch made only of edges and contours",
        "a minimal contour-only drawing",
        "a line art illustration",
        "a black and white line art drawing",
        "a minimal line-art image",
    ],
    "sticker": [
        "a sticker illustration",
        "a colorful sticker image",
        "a cutout sticker graphic",
    ],
    "tattoo": [
        "a tattoo design",
        "a black ink tattoo drawing",
        "a tattoo style illustration",
    ],
    "toy": [
        "a plastic toy figure",
        "a plush toy",
        "a small toy model",
    ],
    "videogame": [
        "a video game rendering",
        "a 3d game character render",
        "a computer game screenshot style image",
    ],
    "drawing": [
        "a hand-drawn drawing",
        "a simple doodle drawing",
        "a colored pencil drawing",
    ],
    "rendering": [
        "a 3d rendered image",
        "a computer generated rendering",
        "a realistic digital rendering",
    ],
    "plastic": [
        "a plastic figure",
        "a shiny plastic object",
        "a molded plastic toy",
    ]
}
